In [2]:
#Numpy case study -ADS virtual Internship
import numpy as np

#create a 1D array
print("1D array")
a=np.array([1,2,3,4,5])
print(a)

#create a 2D array

print("2D array")
b=np.array([[1,2,3],[4,5,6]])
print(b)

#create a 3D array

print("3D array")
c=np.array([[[1,2,3],[4,5,6]],[[4,3,4],[2,3,4]]])
print(c)

#create an array of zeros
c=np.zeros((3,4))
print(c)

#create an array of ones

d=np.ones((2,2))
print(d)

#mathematical operations on numpy
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)

#multiply two arrays
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
f=d*e
print(f)

#matrix multiplication
d=np.array([[1,2],[3,4]])
e=np.array([[5,6],[7,8]])
i=np.dot(d,e)
print(i)




1D array
[1 2 3 4 5]
2D array
[[1 2 3]
 [4 5 6]]
3D array
[[[1 2 3]
  [4 5 6]]

 [[4 3 4]
  [2 3 4]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[5 7 9]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
